data_root: /mnt/imagenet-1k
model: resnet50d
epochs: 200
batch_size: 256
num_workers: 8
img_size: 224
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
warmup_epochs: 5
label_smoothing: 0.1
mixup: 0.2
cutmix: 1.0
reprob: 0.25
aa: rand-m9-mstd0.5
ema: true
seed: 42